calculate_app/urls.py
from django.urls import path,include
from .views import request_handler_calculate

urlpatterns = [
    
    path('',request_handler_calculate,name="main_app")
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('calculate_app.urls'))
]

calculate_app/forms.py
from django import forms

class DestinationFieldForm(forms.Form):
    
    destination = forms.CharField(max_length=200)

calculate_app/views.py
from django.contrib.gis.geoip2 import GeoIP2
from django.http import HttpResponse
from django.shortcuts import render
from geopy import distance as d
from geopy.geocoders import Nominatim

from .forms import DestinationFieldForm



def request_handler_calculate(request):
    if request.method == 'POST':

        form = DestinationFieldForm(request.POST or None)
        

        geolocator = Nominatim(user_agent="calculate_app")
        # ip2 = get_ip_address(request)
        # print(ip2)
        ip = "103.139.234.0" #Dhaka Bangladesh
        country,city,latitude,longitude = get_info(ip)
        origin = (latitude,longitude)

        # print(country,geolocator.geocode(city),latitude,longitude)
        # print(city['city'])

        if form.is_valid():
            
            location = city['city']
            destination_data_fieldform = form.cleaned_data.get('destination')
            destination_details = geolocator.geocode(destination_data_fieldform)
            destination_co_ordinates = (destination_details.latitude,destination_details.longitude)
            distance = d.distance(origin, destination_co_ordinates).km

        return render(request, 'main_app_template.html',{'data': [str(round(distance,2)),city['city'],destination_data_fieldform]})


    else:

        return render(request, 'main_app_template.html',{'hi':'hi'})


def get_info(ip):
    g = GeoIP2()
    country = g.country(ip)
    city = g.city(ip)
    latitude,longitude = g.lat_lon(ip)
    return country,city,latitude,longitude

# AUTOMATIC HOST IP DETECTION > LINE NUMBER 18, 19
# credit yanchenko
# https://stackoverflow.com/questions/4581789/how-do-i-get-user-ip-address-in-django
def get_ip_address(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

calculate_app/templates/main_app_template.html
{% extends 'base.html' %}







{% block content %}
    
{% if data %}

<div class="container-fluid text-sm-center p-5 bg-light"> <!-- bg-light is background color & p-5 is padding -->
    <h1 class="display-2"><strong>{{data.0}}</strong> km</h1>
    <p class="lead">Distance between {{data.1}} and {{data.2}}</p>
</div>
{% else %}
<div class="container-fluid text-sm-center p-5 bg-light"> <!-- bg-light is background color & p-5 is padding -->
    <h1 class="display-2"><strong>00.00 km</strong> </h1>
    <p class="lead">Ready to calculate distance !!</p>
</div>

{% endif %}

{% endblock  %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Distance Calculator</title>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
            <a class="navbar-brand" href="#">GeoDistanceCalculator</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% comment %} <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li> {% endcomment %}
                <li class="nav-item">
                    <a class="nav-link" href="https://www.maxmind.com" target="_blank">This product includes GeoLite2 data created by MaxMind, available from https://www.maxmind.com</a>
                    
                </li>
                </ul>
                <form action= "{% url 'main_app' %}"   class="d-flex" method="POST" autocomplete="off">
                    {% csrf_token %}
                <input id="id_destination" name="destination" class="form-control me-2" type="text" placeholder="Destination" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Calculate</button>
                 
                </form>
            </div>
            </div>
        </nav>
    </div>
  </head>
  <body>
    <div class="container">
        {% block content %}{% endblock content %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>